nome = str (input('Digite Seu nome completo:')).strip()
print('Seu nome com todas as letras maiusculas é {}'.format(nome.upper()))
print('Seu nome com todas as letras minusculas é {}'.format(nome.lower()))
print(len(nome))
print(len('Marcilio'))